const {test}=require('node:test'),assert=require('node:assert/strict');
const {validateBatch,parseRows,amountUnits,toCSV,approvalStep,OWNER,CONTRACT,TOKEN}=require('../.test-build/batch.js');
const {actionData,batchInterface,checkSession,submit}=require('../.test-build/wallet.js');
const {Interface}=require('ethers');
const a='0x1111111111111111111111111111111111111111',b='0x2222222222222222222222222222222222222222';
const rows=[{address:a,amount:'0.000001'},{address:b,amount:'12.345678'}];
test('exact six-decimal totals and roundtrip export',()=>{const batch=validateBatch(rows);assert.equal(batch.total,12345679n);assert.deepEqual(validateBatch(parseRows(toCSV(rows))).rows,batch.rows)});
test('does not lose precision above Number safe integer',()=>{assert.equal(amountUnits('9007199254740993.123456'),9007199254740993123456n)});
for(const amount of ['1e6','1,000','-1','0','0.0000001','1.2.3','Infinity','NaN','01','1.'])test(`rejects invalid amount ${amount}`,()=>assert.throws(()=>amountUnits(amount)));
test('never silently drops malformed import rows',()=>assert.throws(()=>parseRows(`${a},1\nhello\n${b},2`),/line 2/));
test('handles BOM, CSV header, tab, space and CRLF',()=>assert.equal(validateBatch(parseRows(`\uFEFFaddress,amount\r\n${a}\t1\r\n${b} 2`)).total,3000000n));
test('rejects forbidden destinations',()=>{for(const address of [OWNER,CONTRACT,TOKEN,'0x'+'0'.repeat(40)])assert.throws(()=>validateBatch([{address,amount:'1'}]))});
test('rejects broken checksum and empty/incomplete rows',()=>{assert.throws(()=>validateBatch([{address:'0x52908400098527886e0F7030069857D2E4169Ee7',amount:'1'}]));assert.throws(()=>validateBatch([]));assert.throws(()=>validateBatch([...rows,{address:'',amount:''}]))});
test('duplicates remain separate payments and are flagged',()=>{const batch=validateBatch([rows[0],rows[0]]);assert.equal(batch.duplicates.length,1);assert.equal(batch.total,2n);assert.equal(batch.addresses.length,2)});
test('reordered or differently formatted payments match history fingerprint',()=>assert.equal(validateBatch(rows).fingerprint,validateBatch([...rows].reverse()).fingerprint));
test('zero-first allowance sequence and sufficient allowance reuse',()=>{assert.equal(approvalStep(0n,12n),'approve');assert.equal(approvalStep(10n,12n),'reset');assert.equal(approvalStep(12n,12n),'send');assert.equal(approvalStep(20n,12n),'send')});
test('approval targets only the batch contract and exact total',()=>{const batch=validateBatch(rows);const tx=actionData('approve',batch);assert.equal(tx.to,TOKEN);const parsed=new Interface(['function approve(address,uint256)']).parseTransaction(tx);assert.equal(parsed.args[0],CONTRACT);assert.equal(parsed.args[1],batch.total)});
test('send encodes exactly the reviewed arrays for deployed contract',()=>{const batch=validateBatch(rows),tx=actionData('send',batch);assert.equal(tx.to,CONTRACT);const parsed=batchInterface.parseTransaction(tx);assert.equal(parsed.name,'disperseUSDT');assert.deepEqual([...parsed.args[0]],batch.addresses);assert.deepEqual([...parsed.args[1]],batch.amounts)});
test('wallet switch is rejected before submission',async()=>{let sent=false;const p={request:async({method})=>{if(method==='eth_chainId')return '0xaa36a7';if(method==='eth_accounts')return [OWNER];sent=true}};await assert.rejects(()=>submit(p,{account:OWNER}),/changed/);assert.equal(sent,false)});
test('account switch is rejected',async()=>assert.rejects(()=>checkSession({request:async({method})=>method==='eth_chainId'?'0x1':[a]},OWNER),/changed/));
test('submission pins mainnet, sender, destination, data, gas, and zero ETH value',async()=>{let sent;const batch=validateBatch(rows);const p={request:async args=>{if(args.method==='eth_chainId')return '0x1';if(args.method==='eth_accounts')return [OWNER];sent=args;return '0xhash'}};const tx=actionData('send',batch);await submit(p,{account:OWNER,...tx,gas:123n});assert.equal(sent.params[0].chainId,'0x1');assert.equal(sent.params[0].from,OWNER);assert.equal(sent.params[0].value,'0x0');assert.equal(sent.params[0].to,CONTRACT);assert.equal(sent.params[0].gas,'0x7b')});
