'use client';
import ContractSetup from '@/components/contract-setup';
import {discoverAssets, type Portfolio} from '@/lib/assets';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Download, Upload, Plus, Trash2, ArrowUpRight, Wallet, ShieldCheck, RefreshCw, Check, FileText } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Table, TableBody, TableRow, TableCell, TableHead, TableHeader } from '@/components/ui/table';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogCancel } from '@/components/ui/alert-dialog';
import { DEFAULT_CONTRACT, ETH, isNative, formatAmount, type Asset, validateBatch, parseRows, toCSV, approvalStep, type Row } from '@/lib/batch';
import { connectedAccount, loadAsset, verifyContract, readWallet, prepare, submit, friendlyError, isRejected, type Injected, type WalletState, type Plan, type Action } from '@/lib/wallet';
import { loadHistory as loadAllHistory, saveRecord as saveAllRecord, forWallet, unresolved, reconcile, HISTORY_KEY, type RecordEntry } from '@/lib/history';
const DRAFT_KEY='batch-desk:draft:v3';
const CONTRACT_KEY='batch-desk:v3:contract';
const blank=()=>[{address:'',amount:''}];
const short=(s:string)=>s.slice(0,8)+'…'+s.slice(-6);
function download(text:string,name:string,type='text/csv'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const labels:Record<Action,string>={reset:'Reset existing allowance',approve:'Approve batch total',send:'Send batch',revoke:'Revoke unused allowance'};
export default function Home(){
  const [contract,setContract]=useState(DEFAULT_CONTRACT),[account,setAccount]=useState('');
  const [asset,setAsset]=useState<Asset>(ETH),[tokenInput,setTokenInput]=useState(''),[customToken,setCustomToken]=useState(false),[setupMode,setSetupMode]=useState(false);
  const [portfolio,setPortfolio]=useState<Portfolio|null>(null),[assetsLoading,setAssetsLoading]=useState(false),[assetsError,setAssetsError]=useState(''),[assetsRefresh,setAssetsRefresh]=useState(0);
  const holdings=portfolio?.account===account?portfolio.items:[];
  const display=(value:bigint)=>formatAmount(value,asset);
  const CONTRACT=contract, CONFIGURED=!!contract;
  const active=useRef({account,contract});active.current={account,contract};
  const loadHistory=()=>forWallet(loadAllHistory(),active.current.account,active.current.contract);
  const saveRecord=(record:RecordEntry)=>{saveAllRecord(record);return loadHistory()};
  const [rows,setRows]=useState<Row[]>(blank),[title,setTitle]=useState('My batch'),[paste,setPaste]=useState(''),[mode,setMode]=useState('rows');
  const [wallet,setWallet]=useState<WalletState|null>(null),[injected,setInjected]=useState<Injected|null>(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [busy,setBusy]=useState(''),[plan,setPlan]=useState<Plan|null>(null),[reviewed,setReviewed]=useState(false),[allowRepeat,setAllowRepeat]=useState(false),[allowDuplicates,setAllowDuplicates]=useState(false);
  const [history,setHistory]=useState<RecordEntry[]>([]),[clearOpen,setClearOpen]=useState(false),[recover,setRecover]=useState<RecordEntry|null>(null),[recoveryHash,setRecoveryHash]=useState('');
  const [storageOK,setStorageOK]=useState(true);
  const fileRef=useRef<HTMLInputElement>(null),working=useRef(false),epoch=useRef(0);
  const validation=useMemo(()=>{try{return {batch:validateBatch(rows,contract,account,asset),error:''}}catch(e){return {batch:null,error:(e as Error).message}}},[rows,contract,account,asset]);
  const batch=validation.batch;
  const pending=unresolved(history);
  const previous=batch&&history.find(h=>h.kind==='send'&&h.fingerprint===batch.fingerprint&&h.status==='confirmed');
  const step=isNative(asset)?'send':batch&&wallet?approvalStep(wallet.allowance,batch.total):'approve';
  const empty=rows.length===1&&!rows[0].address&&!rows[0].amount;
  useEffect(()=>{
    setSetupMode(new URLSearchParams(location.search).get('setup')==='1');
    try{const selected=new URLSearchParams(location.search).get('contract')||localStorage.getItem(CONTRACT_KEY)||DEFAULT_CONTRACT;if(selected)setContract(selected);const saved=localStorage.getItem(DRAFT_KEY);if(saved){const d=JSON.parse(saved);if(d.asset&&typeof d.asset.address==='string'&&typeof d.asset.symbol==='string'&&Number.isInteger(d.asset.decimals)&&d.asset.decimals>=0&&d.asset.decimals<=255){isNative(d.asset);setAsset(d.asset);setCustomToken(false);setTokenInput(d.asset.address);}if(Array.isArray(d.rows)&&d.rows.length<=500&&d.rows.every((r:Row)=>typeof r.address==='string'&&typeof r.amount==='string')){setRows(d.rows);setTitle(typeof d.title==='string'?d.title:'My batch')}}setHistory(loadHistory());}catch{setStorageOK(false);setError('Browser storage is unavailable or unreadable. Enable site storage before sending; it is needed to track pending transactions.');}
    if(!DEFAULT_CONTRACT&&!new URLSearchParams(location.search).get('contract'))void fetch('/batch-config.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(c=>{if(c&&typeof c==='object'&&'contract' in c&&typeof c.contract==='string'&&c.contract)setContract(c.contract)}).catch(()=>{});
    setReady(true);
    const announce=(event:Event)=>{const d=(event as CustomEvent).detail;if(d?.info?.rdns==='io.metamask')setInjected(d.provider)};
    window.addEventListener('eip6963:announceProvider',announce);window.dispatchEvent(new Event('eip6963:requestProvider'));
    const eth=(window as Window & {ethereum?:Injected}).ethereum;
    const fallback=eth?.providers?.find(p=>p.isMetaMask)??(eth?.isMetaMask?eth:null);if(fallback)setInjected(p=>p??fallback);
    const sync=()=>{try{setHistory(loadHistory())}catch{setStorageOK(false)}};window.addEventListener('storage',sync);
    return()=>{window.removeEventListener('eip6963:announceProvider',announce);window.removeEventListener('storage',sync)};
  },[]);
  useEffect(()=>{if(!ready||!storageOK)return;try{localStorage.setItem(DRAFT_KEY,JSON.stringify({title,rows,asset}))}catch{setStorageOK(false);setError('Unable to save locally. Sending is disabled until browser storage is available.')}},[rows,title,asset,ready,storageOK]);
  useEffect(()=>{setPlan(null);setRecover(null);setReviewed(false);setAllowRepeat(false);setAllowDuplicates(false);epoch.current++;try{setHistory(loadHistory())}catch{setStorageOK(false)}},[rows,account,contract,asset]);
  useEffect(()=>{
    if(!injected)return;
    const changed=()=>{epoch.current++;setAccount('');setWallet(null);setHistory([]);setPlan(null);setReviewed(false);setNotice('Wallet changed. Loading the selected account…');void connectedAccount(injected).then(setAccount).catch(e=>setError(friendlyError(e)));};
    injected.on?.('accountsChanged',changed);injected.on?.('chainChanged',changed);injected.on?.('disconnect',changed);
    void connectedAccount(injected).then(setAccount).catch(()=>{});
    return()=>{injected.removeListener?.('accountsChanged',changed);injected.removeListener?.('chainChanged',changed);injected.removeListener?.('disconnect',changed)};
  },[injected]);
  useEffect(()=>{if(!injected||!account||!contract)return;let stopped=false;setWallet(null);void readWallet(injected,contract,asset).then(state=>{if(!stopped&&state.account===account){setWallet(state);setError('');setNotice('Wallet connected.')}}).catch(e=>{if(!stopped)setError(friendlyError(e))});return()=>{stopped=true}},[account,contract,injected,asset]);
  useEffect(()=>{
    setPortfolio(null);setAssetsError('');
    if(!injected||!account){setAssetsLoading(false);return;}
    const controller=new AbortController();setAssetsLoading(true);
    void discoverAssets(injected,account,controller.signal).then(result=>{if(!controller.signal.aborted){setPortfolio(result);setAssetsError(result.warning)}}).catch(e=>{if(!controller.signal.aborted)setAssetsError(friendlyError(e))}).finally(()=>{if(!controller.signal.aborted)setAssetsLoading(false)});
    return()=>controller.abort();
  },[injected,account,assetsRefresh]);
  // Optional read-only WebMCP preview: never exposes signing or payment actions.
  const currentRows=useRef(rows);currentRows.current=rows;
  useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'preview_batch',description:'Read the current batch validation and total. Does not connect a wallet or submit a transaction.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>{try{const b=validateBatch(currentRows.current,contract,account,asset);return {recipients:b.rows,total:formatAmount(b.total,asset),asset,duplicateAddresses:b.duplicates,contract:CONTRACT,network:'Ethereum mainnet',submitted:false}}catch(e){return {valid:false,error:(e as Error).message}}}},{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[contract,account,asset]);
  async function run(label:string,fn:()=>Promise<void>){if(working.current)return;working.current=true;setBusy(label);setError('');try{await fn()}catch(e){setError(friendlyError(e))}finally{working.current=false;setBusy('')}}
  async function refresh(){if(!injected)throw new Error('Open this page in Chrome with MetaMask installed.');const generation=epoch.current;const state=await readWallet(injected,contract,asset);if(generation!==epoch.current)throw new Error('Wallet changed during the check. Connect again.');setWallet(state);setAccount(state.account);const entries=forWallet(loadAllHistory(),state.account,contract);for(const entry of entries.filter(h=>h.hash&&['pending','unknown'].includes(h.status))){const updated=await reconcile(injected,entry);saveRecord(updated)}setHistory(loadHistory());}
  async function connect(){if(!injected)throw new Error('Open this page in Chrome with your MetaMask extension.');await injected.request({method:'eth_requestAccounts'});const selected=await connectedAccount(injected);setAccount(selected);if(contract)await refresh();else setNotice('Wallet connected. The shared contract is awaiting setup.');}
  async function switchWallet(){if(!injected)throw new Error('Open this page in Chrome with MetaMask.');await injected.request({method:'wallet_requestPermissions',params:[{eth_accounts:{}}]});await connect();}
  async function selectContract(address:string){if(!injected)throw new Error('Connect MetaMask first.');const generation=epoch.current;const verified=await verifyContract(injected,address);if(generation!==epoch.current)throw new Error('Wallet changed during verification. Try again.');localStorage.setItem(CONTRACT_KEY,verified);setWallet(null);setContract(verified);setNotice('Shared contract selected. Any connected wallet can use it.');}
  function importText(text:string){try{const imported=parseRows(text);validateBatch(imported,contract,account,asset);setRows(imported);setPaste('');setMode('rows');setError('');setNotice(`${imported.length} recipients imported. Review the full list before sending.`)}catch(e){setError(friendlyError(e))}}
  async function review(kind:Action){if(!injected||(!batch&&kind!=='revoke'))throw new Error('Connect your wallet and complete the recipient list.');if(unresolved(loadHistory()))throw new Error('Resolve the pending transaction in history before requesting another.');const generation=epoch.current;const prepared=await prepare(injected,kind,batch??{rows:[],addresses:[],amounts:[],total:0n,fingerprint:'revoke',duplicates:[],asset},contract);if(generation!==epoch.current)throw new Error('Details changed. Review again.');setPlan(prepared);setReviewed(false);}
  async function sign(){
    if(!plan||!injected||!reviewed||!storageOK)return;
    if(plan.kind!=='revoke'&&plan.batch.fingerprint!==batch?.fingerprint)throw new Error('The batch changed. Review again.');
    if(!navigator.locks)throw new Error('Use a current Chrome version; transaction locking is required.');
    await navigator.locks.request(HISTORY_KEY,{ifAvailable:true},async lock=>{
      if(!lock)throw new Error('Another tab is preparing a transaction. Finish there first.');
      const existing=loadHistory();if(unresolved(existing))throw new Error('A transaction is already pending. Check history.');
      if(plan.kind==='send'&&existing.some(h=>h.kind==='send'&&h.fingerprint===plan.batch.fingerprint&&h.status==='confirmed')&&!allowRepeat)throw new Error('This batch has already been sent. Confirm that a repeat payment is intended.');
      const generation=epoch.current;
      const fresh=await prepare(injected,plan.kind,plan.batch,plan.contract);
      if(generation!==epoch.current)throw new Error('Wallet changed. Review again.');
      if(fresh.account!==plan.account||fresh.contract!==plan.contract||fresh.to!==plan.to||fresh.data!==plan.data||fresh.value!==plan.value)throw new Error('Transaction details changed. Review again.');
      if(Number(fresh.fee)>Number(plan.fee)*1.2){setPlan(fresh);setReviewed(false);throw new Error('The estimated fee increased. Review the updated estimate.');}
      const nonce=Number(BigInt(await injected.request({method:'eth_getTransactionCount',params:[plan.account,'pending']})));
      let record:RecordEntry={id:crypto.randomUUID(),title,kind:plan.kind,fingerprint:plan.batch.fingerprint,total:formatAmount(plan.batch.total,plan.batch.asset),count:plan.batch.rows.length,status:'signing',created:new Date().toISOString(),data:plan.data,to:plan.to,nonce,from:plan.account,contract:plan.contract,asset:plan.batch.asset,value:plan.value.toString()};
      setHistory(saveRecord(record));setPlan(null);setAllowRepeat(false);setNotice('Review the request in MetaMask and sign with the connected wallet.');
      try{const hash=await submit(injected,fresh);record={...record,hash,status:'pending'};setHistory(saveRecord(record));setNotice('Transaction submitted. Its receipt will appear below.');}
      catch(e){record={...record,status:isRejected(e)?'rejected':'unknown'};setHistory(saveRecord(record));throw e}
    });
  }
  useEffect(()=>{if(!injected||!history.some(h=>h.status==='pending'&&h.hash))return;let stopped=false;let checking=false;const timer=setInterval(async()=>{if(checking)return;checking=true;try{for(const h of loadHistory().filter(x=>x.status==='pending'&&x.hash)){const updated=await reconcile(injected,h);if(stopped)return;if(updated.status!==h.status){saveRecord(updated);if(updated.status==='confirmed'){setAssetsRefresh(v=>v+1);setNotice(updated.kind==='send'?'Batch confirmed. Transfers completed.':'Allowance transaction confirmed. Review the next step.');}}}if(!stopped){const entries=loadHistory();const state=await readWallet(injected,contract,asset);if(!stopped){setWallet(state);setHistory(entries)}}}catch{}finally{checking=false}},12000);return()=>{stopped=true;clearInterval(timer)}},[injected,history,contract,account,asset]);
  async function recoverByHash(){if(!recover||!injected)return;if(!/^0x[\da-fA-F]{64}$/.test(recoveryHash))throw new Error('Enter the transaction hash from MetaMask activity.');const updated=await reconcile(injected,{...recover,hash:recoveryHash},true);if(updated.status==='unknown')throw new Error('That transaction does not match this request. Check the hash in MetaMask.');setHistory(saveRecord(updated));setRecover(null);setRecoveryHash('');}
  async function clearUnsent(){if(!recover||!injected)return;await connectedAccount(injected);if(active.current.account!==recover.from)throw new Error('Switch back to the wallet that made this request.');const [latest,pendingNonce]=await Promise.all(['latest','pending'].map(tag=>injected.request({method:'eth_getTransactionCount',params:[recover.from,tag]})));if(Number(BigInt(latest))!==recover.nonce||Number(BigInt(pendingNonce))!==recover.nonce)throw new Error('The account nonce changed or a transaction is pending. Locate its hash in MetaMask instead.');setHistory(saveRecord({...recover,status:'rejected'}));setRecover(null);setNotice('Unsent request cleared after checking the account nonce.');}
  const disabled=!!busy||pending||!ready;
  const tokenReady=!customToken||(!isNative(asset)&&tokenInput.trim().toLowerCase()===asset.address.toLowerCase());
  const canReview=tokenReady&&!!batch&&!!wallet&&storageOK&&!disabled&&(!batch.duplicates.length||allowDuplicates)&&(!previous||allowRepeat);
  return <main className="desk">
    <header><div className="brand"><span className="mark">↗</span> Batch <b>Desk</b></div><span className="network">● Ethereum mainnet</span><button className="wallet-button" disabled={!!busy} onClick={()=>run('Connecting…',connect)}><Wallet size={16}/>{account?short(account):'Connect MetaMask'}</button>{account&&<button className="text-button" disabled={!!busy} onClick={()=>run('Selecting account…',switchWallet)}>Change wallet</button>}</header>
    <div className="titlebar"><div><p className="eyebrow">SHARED CONTRACT · YOUR WALLET</p><h1>One batch. All your payments.</h1></div><div className="contract-badge"><ShieldCheck size={18}/><div>Shared contract<a href={`https://etherscan.io/address/${CONTRACT}`} target="_blank" rel="noreferrer">{short(CONTRACT)} ↗</a></div></div></div>
    {setupMode&&<ContractSetup injected={injected} account={account} contract={contract} busy={!!busy} onSelect={selectContract} onConnect={()=>run('Connecting…',connect)}/> }
    {ready&&!CONFIGURED&&!setupMode&&<div className="message">The shared contract is being set up. Sending will be available once configuration is complete.</div>}
    <div className="steps"><span className="active"><b>01</b> Configure</span><i/><span><b>02</b> {isNative(asset)?'Review':'Review & approve'}</span><i/><span><b>03</b> Sign & send</span></div>
    {error&&<div className="message error" role="alert">{error}{/mainnet/.test(error)&&<button className="quiet" disabled={!!busy} onClick={()=>run('Switching…',async()=>{await injected?.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x1'}]});await refresh()})}>Switch to Ethereum</button>}</div>}
    {notice&&<div className="message" role="status">{notice}</div>}
    <div className="workspace"><div><section className="paper">
      <div className="section-head"><div><label className="small-label" htmlFor="batch-name">BATCH NAME</label><input id="batch-name" className="name-input" value={title} maxLength={80} disabled={disabled} onChange={e=>setTitle(e.target.value)}/></div><span className="saved"><Check size={14}/>{ready&&storageOK?'Saved in this browser':'Local draft'}</span></div>
      <div className="asset-picker"><label className="small-label" htmlFor="asset-kind">SEND FROM YOUR WALLET</label><div className="asset-row"><select id="asset-kind" disabled={disabled} value={customToken?'custom':asset.address} onChange={e=>{
        const address=e.target.value;setPlan(null);setReviewed(false);setError('');epoch.current++;
        if(address==='custom'){setCustomToken(true);setTokenInput('');return;}
        setCustomToken(false);
        if(address===ETH.address){setWallet(null);setAsset({...ETH});return;}
        void run('Loading token…',async()=>{if(!injected)throw new Error('Connect MetaMask to load this token.');const generation=epoch.current;const selected=await loadAsset(injected,address);if(generation!==epoch.current)throw new Error('Wallet changed while loading tokens. Try again.');setWallet(null);setAsset(selected);});
      }}><option value={ETH.address}>ETH · Ether{holdings[0]?.address===ETH.address?' · '+formatAmount(holdings[0].balance,ETH):''}</option>
      {holdings.filter(h=>h.address!==ETH.address).map(h=><option key={h.address} value={h.address}>{h.symbol} · {h.decimals===null?'Balance unavailable':formatAmount(h.balance,{...h,decimals:h.decimals})} · {short(h.address)}</option>)}
      {!isNative(asset)&&!holdings.some(h=>h.address===asset.address)&&<option value={asset.address}>{asset.symbol} · Selected token · {short(asset.address)}</option>}
      <option value="custom">Add a token manually…</option></select>
      <button className="text-button" disabled={disabled||!account||assetsLoading} onClick={()=>setAssetsRefresh(v=>v+1)}><RefreshCw size={14}/>{assetsLoading?'Loading tokens…':'Refresh tokens'}</button>
      {customToken&&<><input aria-label="ERC-20 token contract" className="address-input" placeholder="0x… token contract address" value={tokenInput} disabled={disabled} onChange={e=>{setTokenInput(e.target.value);setPlan(null);setReviewed(false);epoch.current++;}}/><button className="quiet" disabled={disabled||!injected||!account||!tokenInput.trim()} onClick={()=>run('Loading token…',async()=>{if(!injected)return;const generation=epoch.current;const selected=await loadAsset(injected,tokenInput);if(generation!==epoch.current)throw new Error('Wallet changed while loading the token. Try again.');setPlan(null);setWallet(null);setAsset(selected);setCustomToken(false);setNotice(`${selected.symbol} loaded. Check the token address and batch amounts.`);})}>Load token</button></>}
      </div>{assetsError&&<p className="validation" role="status">{assetsError}</p>}
      <p className="asset-caption">{!account?'Connect MetaMask to see the tokens in your wallet.':assetsLoading?'Finding your Ethereum tokens…':`${holdings.filter(h=>h.address!==ETH.address).length} tokens found in this wallet.`} {customToken?'Enter a token address to continue.':<>Selected: <b>{asset.symbol}</b> · {asset.decimals} decimals{!isNative(asset)&&<> · <a href={`https://etherscan.io/token/${asset.address}`} target="_blank" rel="noreferrer">{asset.address}</a></>}</>}</p></div>
      <Tabs value={mode} onValueChange={v=>setMode(String(v))}><div className="editor-tools"><TabsList><TabsTrigger value="rows">Enter recipients</TabsTrigger><TabsTrigger value="paste">Paste a list</TabsTrigger></TabsList><button className="text-button" disabled={disabled} onClick={()=>fileRef.current?.click()}><Upload size={15}/>Import CSV</button><input ref={fileRef} type="file" accept=".csv,.txt,text/csv,text/plain" hidden onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>200000)setError('The import is too large. Use at most 500 rows.');else importText(await f.text())}e.target.value=''}}/></div>
      <TabsContent value="rows"><Table><TableHeader><TableRow><TableHead>#</TableHead><TableHead>Ethereum recipient</TableHead><TableHead className="amount-heading">Amount · {asset.symbol}</TableHead><TableHead><span className="sr-only">Remove</span></TableHead></TableRow></TableHeader><TableBody>{rows.map((row,i)=><TableRow key={i}><TableCell>{String(i+1).padStart(2,'0')}</TableCell><TableCell><input className="address-input" spellCheck={false} autoComplete="off" aria-label={`Recipient ${i+1}`} placeholder="0x… Ethereum address" value={row.address} disabled={disabled} onChange={e=>setRows(rows.map((r,j)=>i===j?{...r,address:e.target.value}:r))}/></TableCell><TableCell><input className="amount-input" inputMode="decimal" aria-label={`Amount ${i+1} in ${asset.symbol}`} placeholder="0.00" value={row.amount} disabled={disabled} onChange={e=>setRows(rows.map((r,j)=>i===j?{...r,amount:e.target.value}:r))}/></TableCell><TableCell><button className="icon-button" aria-label={`Remove recipient ${i+1}`} disabled={disabled} onClick={()=>setRows(rows.length===1?blank():rows.filter((_,j)=>j!==i))}><Trash2 size={15}/></button></TableCell></TableRow>)}</TableBody></Table><div className="editor-bottom"><button className="quiet" disabled={disabled||rows.length>=500} onClick={()=>setRows([...rows,{address:'',amount:''}])}><Plus size={15}/>Add recipient</button><span>{rows.length} {rows.length===1?'row':'rows'} · up to {asset.decimals} decimals</span></div></TabsContent>
      <TabsContent value="paste"><div className="paste-panel"><label htmlFor="paste-list">One address and {asset.symbol} amount per line. Commas, tabs, or spaces.</label><textarea id="paste-list" placeholder={'0x…address, 25.50\n0x…address, 100'} rows={7} spellCheck={false} value={paste} disabled={disabled} onChange={e=>setPaste(e.target.value)}/><button className="quiet" disabled={disabled||!paste.trim()} onClick={()=>importText(paste)}>Use this list</button><p>Import replaces the current rows only after every line passes validation.</p></div></TabsContent></Tabs>
      {!empty&&validation.error&&<div className="validation" role="status">{validation.error}</div>}
      <div className="paper-footer"><button className="text-button" disabled={!batch||!!busy} onClick={()=>{try{download(toCSV(rows,asset,contract,account),'batch.csv')}catch(e){setError(friendlyError(e))}}}><Download size={14}/>Export CSV</button><button className="text-button" disabled={disabled} onClick={()=>setClearOpen(true)}>New batch</button></div>
    </section>
    <div className="privacy-note"><ShieldCheck size={16}/><span>Drafts and history stay in this browser. Payments are public on Ethereum after you sign.</span></div>
    <section className="history"><div className="section-head"><h2>Transaction history</h2><button className="text-button" disabled={!!busy||!injected} onClick={()=>run('Checking receipts…',refresh)}><RefreshCw size={14}/>Refresh</button></div>{history.length===0?<div className="history-empty"><FileText size={26}/><div>No payments sent from this interface yet.<small>Pending transactions and receipts will appear here.</small></div></div>:<div className="history-list">{history.map(h=><article key={h.id}><div><strong>{h.kind==='send'?h.title:labels[h.kind]}</strong><small>{new Date(h.created).toLocaleString()} · {h.kind==='send'?`${h.count} recipients · ${h.total} ${h.asset?.symbol??'USDT'}`:h.kind==='approve'?`${h.total} ${h.asset?.symbol??'USDT'}`:`0 ${h.asset?.symbol??'USDT'} allowance`}</small></div><div className="history-status"><span className={`status ${h.status}`}>{h.status==='signing'?'Awaiting signature':h.status}</span>{h.hash&&<a href={`https://etherscan.io/tx/${h.hash}`} target="_blank" rel="noreferrer">View transaction ↗</a>}{['pending','signing','unknown'].includes(h.status)&&<button className="text-button" onClick={()=>{setRecover(h);setRecoveryHash('')}}>Resolve request</button>}</div></article>)}</div>}{history.length>0&&<button className="text-button export-history" onClick={()=>download(JSON.stringify(history,null,2),'batch-transaction-history.json','application/json')}><Download size={14}/>Export history</button>}</section>
    </div><aside><section className="summary"><p className="eyebrow">BATCH TOTAL</p><div className="total">{batch?display(batch.total):'0.00'} <small>{asset.symbol}</small></div><div className="summary-line"><span>Recipients</span><b>{batch?.rows.length??'—'}</b></div><div className="summary-line"><span>Available {asset.symbol}</span><b>{wallet?display(wallet.balance):'Connect wallet'}</b></div><div className="summary-line"><span>Contract fee</span><b>0</b></div>{!isNative(asset)&&<div className="summary-line"><span>Allowance</span><b>{wallet?display(wallet.allowance)+' '+asset.symbol:'—'}</b></div>}<div className="summary-divider"/>
      {batch&&batch.duplicates.length>0&&<label className="check-line warning"><Checkbox checked={allowDuplicates} onCheckedChange={v=>setAllowDuplicates(v===true)}/><span>{batch.duplicates.length} repeated address(es). Pay each row separately.</span></label>}
      {previous&&<label className="check-line warning"><Checkbox checked={allowRepeat} onCheckedChange={v=>setAllowRepeat(v===true)}/><span>This payment list was already sent. I intend to pay it again.</span></label>}
      <p>{pending?'A request is still open. Check transaction history before sending again.':!wallet?'Connect any of your accounts through MetaMask.':isNative(asset)?'ETH needs no token approval. Review the batch and network fee, then sign.':step==='reset'?'Reset the existing allowance to zero before approving this batch.':step==='approve'?'Approve only this batch’s total, then review and send the payment.':'Allowance is ready. Review every recipient and the network fee before sending.'}</p>
      <button className="primary" disabled={!!busy||(!!account&&(!CONFIGURED||!wallet||!canReview))} onClick={()=>wallet?run('Checking batch…',()=>review(step)):run('Connecting…',connect)}>{busy||(!wallet?'Connect MetaMask':labels[step])}<ArrowUpRight size={17}/></button>
      <p className="ledger-note">You sign from the connected wallet.<br/>Network fees are paid separately in ETH.</p>
      {!isNative(asset)&&wallet&&wallet.allowance>0n&&<button className="revoke-button" disabled={!storageOK||disabled||!tokenReady} onClick={()=>run('Checking allowance…',()=>review('revoke'))}>Revoke unused allowance</button>}
    </section><details className="contract-details"><summary>Contract & wallet details</summary><label>Batch contract</label><a href={`https://etherscan.io/address/${CONTRACT}`} target="_blank" rel="noreferrer">{CONTRACT}</a><label>Connected sender</label><span>{account||'Connect a wallet'}</span><label>Selected asset</label>{isNative(asset)?<span>ETH · Native Ether</span>:<a href={`https://etherscan.io/token/${asset.address}`} target="_blank" rel="noreferrer">{asset.symbol} · {asset.address}</a>}<p>Wallet token discovery uses Blockscout’s public Ethereum index. The lookup sends your connected public address to Blockscout and may lag recent transfers. Selected token details and spending balances are checked through MetaMask.</p><p>A failed transfer reverts the batch. Token-defined transfer fees and rebasing can affect the amount recipients receive.</p></details></aside></div>
    <footer><span>Batch Desk</span><span>Ethereum mainnet · SharedBatch</span></footer>
    <Dialog open={!!plan} onOpenChange={open=>{if(!open&&!busy)setPlan(null)}}><DialogContent className="review-dialog" showCloseButton={!busy}><DialogTitle>{plan?labels[plan.kind]:''}</DialogTitle><DialogDescription>Ethereum mainnet · Sender {plan?.account||account}</DialogDescription>{error&&<p role="alert" className="validation">{error}</p>}{plan&&<><div className="review-amount">{plan.kind==='reset'||plan.kind==='revoke'?'0':formatAmount(plan.batch.total,plan.batch.asset)} <small>{plan.batch.asset.symbol} {plan.kind==='send'?'to recipients':'allowance'}</small></div><p className="review-address">Asset: {plan.batch.asset.symbol}<code>{isNative(plan.batch.asset)?'Native ETH':plan.batch.asset.address}</code></p><p className="review-address">{plan.kind==='send'?'Batch contract':'Approved spender'}<code>{CONTRACT}</code></p>{plan.kind==='send'&&<div className="review-recipients"><Table><TableHeader><TableRow><TableHead>Recipient</TableHead><TableHead>{plan.batch.asset.symbol}</TableHead></TableRow></TableHeader><TableBody>{plan.batch.rows.map((r,i)=><TableRow key={i}><TableCell className="full-address">{r.address}</TableCell><TableCell>{r.amount}</TableCell></TableRow>)}</TableBody></Table></div>}<p>Estimated maximum network fee: <b>{plan.fee} ETH</b><br/><small>MetaMask displays the final fee before you sign.</small></p><label className="check-line"><Checkbox checked={reviewed} disabled={!!busy} onCheckedChange={v=>setReviewed(v===true)}/><span>I checked {plan.kind==='send'?'every recipient and amount':'the spender and allowance amount'}.</span></label><button className="primary" disabled={!reviewed||!!busy} onClick={()=>run('Waiting for wallet…',sign)}>{busy||'Continue to MetaMask'}<ArrowUpRight size={17}/></button></>}</DialogContent></Dialog>
    <AlertDialog open={clearOpen} onOpenChange={setClearOpen}><AlertDialogContent><AlertDialogTitle>Start a new batch?</AlertDialogTitle><AlertDialogDescription>This clears the current draft. Export it first if you want to use it again. Transaction history stays saved.</AlertDialogDescription><div className="actions"><AlertDialogCancel>Keep editing</AlertDialogCancel><button className="quiet" onClick={()=>{setRows(blank());setTitle('My batch');setClearOpen(false);setNotice('New batch ready.')}}>New batch</button></div></AlertDialogContent></AlertDialog>
    <Dialog open={!!recover} onOpenChange={open=>{if(!open)setRecover(null)}}><DialogContent><DialogTitle>Resolve an unfinished request</DialogTitle><DialogDescription>Check MetaMask Activity first. If the transaction was submitted, paste its transaction hash. Do not repeat the payment.</DialogDescription>{error&&<p role="alert" className="validation">{error}</p>}<input aria-label="Transaction hash" placeholder="0x… transaction hash" value={recoveryHash} onChange={e=>setRecoveryHash(e.target.value)}/><button className="quiet" disabled={!!busy} onClick={()=>run('Checking transaction…',recoverByHash)}>Find transaction</button><p className="muted">If you rejected or closed the request in MetaMask and nothing was submitted, clear it below. The account nonce will be checked first.</p><button className="text-button" disabled={!!busy} onClick={()=>run('Checking account nonce…',clearUnsent)}>I canceled it in MetaMask — check & clear</button></DialogContent></Dialog>
  </main>
}
