'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Download, Upload, Plus, Trash2, ArrowUpRight, Wallet, ShieldCheck, RefreshCw, Check, FileText } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Table, TableBody, TableRow, TableCell, TableHead, TableHeader } from '@/components/ui/table';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogCancel } from '@/components/ui/alert-dialog';
import { OWNER, CONTRACT, TOKEN, CONFIGURED, validateBatch, parseRows, toCSV, approvalStep, usdt, type Row } from '@/lib/batch';
import { readWallet, prepare, submit, friendlyError, isRejected, type Injected, type WalletState, type Plan, type Action } from '@/lib/wallet';
import { loadHistory, saveRecord, unresolved, reconcile, HISTORY_KEY, type RecordEntry } from '@/lib/history';
const DRAFT_KEY='batch-desk:draft:v1';
const blank=()=>[{address:'',amount:''}];
const short=(s:string)=>s.slice(0,8)+'…'+s.slice(-6);
function download(text:string,name:string,type='text/csv'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const labels:Record<Action,string>={reset:'Reset existing allowance',approve:'Approve batch total',send:'Send batch',revoke:'Revoke unused allowance'};
export default function Home(){
  const [rows,setRows]=useState<Row[]>(blank),[title,setTitle]=useState('My USDT batch'),[paste,setPaste]=useState(''),[mode,setMode]=useState('rows');
  const [wallet,setWallet]=useState<WalletState|null>(null),[injected,setInjected]=useState<Injected|null>(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [busy,setBusy]=useState(''),[plan,setPlan]=useState<Plan|null>(null),[reviewed,setReviewed]=useState(false),[allowRepeat,setAllowRepeat]=useState(false),[allowDuplicates,setAllowDuplicates]=useState(false);
  const [history,setHistory]=useState<RecordEntry[]>([]),[clearOpen,setClearOpen]=useState(false),[recover,setRecover]=useState<RecordEntry|null>(null),[recoveryHash,setRecoveryHash]=useState('');
  const [storageOK,setStorageOK]=useState(true);
  const fileRef=useRef<HTMLInputElement>(null),working=useRef(false),epoch=useRef(0);
  const validation=useMemo(()=>{try{return {batch:validateBatch(rows),error:''}}catch(e){return {batch:null,error:(e as Error).message}}},[rows]);
  const batch=validation.batch;
  const pending=unresolved(history);
  const previous=batch&&history.find(h=>h.kind==='send'&&h.fingerprint===batch.fingerprint&&h.status==='confirmed');
  const step=batch&&wallet?approvalStep(wallet.allowance,batch.total):'approve';
  const empty=rows.length===1&&!rows[0].address&&!rows[0].amount;
  useEffect(()=>{
    try{const saved=localStorage.getItem(DRAFT_KEY);if(saved){const d=JSON.parse(saved);if(Array.isArray(d.rows)&&d.rows.length<=500&&d.rows.every((r:Row)=>typeof r.address==='string'&&typeof r.amount==='string')){setRows(d.rows);setTitle(typeof d.title==='string'?d.title:'My USDT batch')}}setHistory(loadHistory());}catch{setStorageOK(false);setError('Browser storage is unavailable or unreadable. Enable site storage before sending; it is needed to track pending transactions.');}
    setReady(true);
    const announce=(event:Event)=>{const d=(event as CustomEvent).detail;if(d?.info?.rdns==='io.metamask')setInjected(d.provider)};
    window.addEventListener('eip6963:announceProvider',announce);window.dispatchEvent(new Event('eip6963:requestProvider'));
    const eth=(window as Window & {ethereum?:Injected}).ethereum;
    const fallback=eth?.providers?.find(p=>p.isMetaMask)??(eth?.isMetaMask?eth:null);if(fallback)setInjected(p=>p??fallback);
    const sync=()=>{try{setHistory(loadHistory())}catch{setStorageOK(false)}};window.addEventListener('storage',sync);
    return()=>{window.removeEventListener('eip6963:announceProvider',announce);window.removeEventListener('storage',sync)};
  },[]);
  useEffect(()=>{if(!ready||!storageOK)return;try{localStorage.setItem(DRAFT_KEY,JSON.stringify({title,rows}))}catch{setStorageOK(false);setError('Unable to save locally. Sending is disabled until browser storage is available.')}},[rows,title,ready,storageOK]);
  useEffect(()=>{setPlan(null);setReviewed(false);setAllowRepeat(false);setAllowDuplicates(false);epoch.current++},[rows]);
  useEffect(()=>{
    if(!injected)return;
    const changed=()=>{epoch.current++;setWallet(null);setPlan(null);setReviewed(false);setNotice('Wallet changed. Reconnect to verify your account and network.');};
    injected.on?.('accountsChanged',changed);injected.on?.('chainChanged',changed);injected.on?.('disconnect',changed);
    return()=>{injected.removeListener?.('accountsChanged',changed);injected.removeListener?.('chainChanged',changed);injected.removeListener?.('disconnect',changed)};
  },[injected]);
  // Optional read-only WebMCP preview: never exposes signing or payment actions.
  const currentRows=useRef(rows);currentRows.current=rows;
  useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'preview_usdt_batch',description:'Read the current batch validation and total. Does not connect a wallet or submit a transaction.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>{try{const b=validateBatch(currentRows.current);return {recipients:b.rows,total:usdt(b.total),duplicateAddresses:b.duplicates,contract:CONTRACT,network:'Ethereum mainnet',submitted:false}}catch(e){return {valid:false,error:(e as Error).message}}}},{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[]);
  async function run(label:string,fn:()=>Promise<void>){if(working.current)return;working.current=true;setBusy(label);setError('');try{await fn()}catch(e){setError(friendlyError(e))}finally{working.current=false;setBusy('')}}
  async function refresh(){if(!injected)throw new Error('Open this page in Chrome with MetaMask installed.');const generation=epoch.current;const state=await readWallet(injected);if(generation!==epoch.current)throw new Error('Wallet changed during the check. Connect again.');setWallet(state);const entries=loadHistory();for(const entry of entries.filter(h=>h.hash&&['pending','unknown'].includes(h.status))){const updated=await reconcile(injected,entry);saveRecord(updated)}setHistory(loadHistory());}
  async function connect(){if(!CONFIGURED)throw new Error('Set up config.local.json and rebuild before connecting a wallet.');if(!injected)throw new Error('Open this page in Chrome with your MetaMask extension.');await injected.request({method:'eth_requestAccounts'});await refresh();setNotice('Owner account and deployed contract verified.');}
  function importText(text:string){try{const imported=parseRows(text);validateBatch(imported);setRows(imported);setPaste('');setMode('rows');setError('');setNotice(`${imported.length} recipients imported. Review the full list before sending.`)}catch(e){setError(friendlyError(e))}}
  async function review(kind:Action){if(!injected||(!batch&&kind!=='revoke'))throw new Error('Connect your wallet and complete the recipient list.');if(unresolved(loadHistory()))throw new Error('Resolve the pending transaction in history before requesting another.');const generation=epoch.current;const prepared=await prepare(injected,kind,batch??{rows:[],addresses:[],amounts:[],total:0n,fingerprint:'revoke',duplicates:[]});if(generation!==epoch.current)throw new Error('Details changed. Review again.');setPlan(prepared);setReviewed(false);}
  async function sign(){
    if(!plan||!injected||!reviewed||!storageOK)return;
    if(plan.kind!=='revoke'&&plan.batch.fingerprint!==batch?.fingerprint)throw new Error('The batch changed. Review again.');
    if(!navigator.locks)throw new Error('Use a current Chrome version; transaction locking is required.');
    await navigator.locks.request(HISTORY_KEY,{ifAvailable:true},async lock=>{
      if(!lock)throw new Error('Another tab is preparing a transaction. Finish there first.');
      const existing=loadHistory();if(unresolved(existing))throw new Error('A transaction is already pending. Check history.');
      if(plan.kind==='send'&&existing.some(h=>h.kind==='send'&&h.fingerprint===plan.batch.fingerprint&&h.status==='confirmed')&&!allowRepeat)throw new Error('This batch has already been sent. Confirm that a repeat payment is intended.');
      const generation=epoch.current;
      const fresh=await prepare(injected,plan.kind,plan.batch);
      if(generation!==epoch.current)throw new Error('Wallet changed. Review again.');
      if(fresh.to!==plan.to||fresh.data!==plan.data)throw new Error('Transaction details changed. Review again.');
      if(Number(fresh.fee)>Number(plan.fee)*1.2){setPlan(fresh);setReviewed(false);throw new Error('The estimated fee increased. Review the updated estimate.');}
      const nonce=Number(BigInt(await injected.request({method:'eth_getTransactionCount',params:[OWNER,'pending']})));
      let record:RecordEntry={id:crypto.randomUUID(),title,kind:plan.kind,fingerprint:plan.batch.fingerprint,total:usdt(plan.batch.total),count:plan.batch.rows.length,status:'signing',created:new Date().toISOString(),data:plan.data,to:plan.to,nonce};
      setHistory(saveRecord(record));setPlan(null);setAllowRepeat(false);setNotice('Review the request in MetaMask and sign on your Ledger.');
      try{const hash=await submit(injected,fresh);record={...record,hash,status:'pending'};setHistory(saveRecord(record));setNotice('Transaction submitted. Its receipt will appear below.');}
      catch(e){record={...record,status:isRejected(e)?'rejected':'unknown'};setHistory(saveRecord(record));throw e}
    });
  }
  useEffect(()=>{if(!injected||!history.some(h=>h.status==='pending'&&h.hash))return;let stopped=false;let checking=false;const timer=setInterval(async()=>{if(checking)return;checking=true;try{for(const h of loadHistory().filter(x=>x.status==='pending'&&x.hash)){const updated=await reconcile(injected,h);if(stopped)return;if(updated.status!==h.status){saveRecord(updated);if(updated.status==='confirmed')setNotice(updated.kind==='send'?'Batch confirmed. All recipients were paid.':'Allowance transaction confirmed. Review the next step.');}}if(!stopped){const entries=loadHistory();const state=await readWallet(injected);if(!stopped){setWallet(state);setHistory(entries)}}}catch{}finally{checking=false}},12000);return()=>{stopped=true;clearInterval(timer)}},[injected,history]);
  async function recoverByHash(){if(!recover||!injected)return;if(!/^0x[\da-fA-F]{64}$/.test(recoveryHash))throw new Error('Enter the transaction hash from MetaMask activity.');const updated=await reconcile(injected,{...recover,hash:recoveryHash},true);if(updated.status==='unknown')throw new Error('That transaction does not match this request. Check the hash in MetaMask.');setHistory(saveRecord(updated));setRecover(null);setRecoveryHash('');}
  async function clearUnsent(){if(!recover||!injected)return;await readWallet(injected);const [latest,pendingNonce]=await Promise.all(['latest','pending'].map(tag=>injected.request({method:'eth_getTransactionCount',params:[OWNER,tag]})));if(Number(BigInt(latest))!==recover.nonce||Number(BigInt(pendingNonce))!==recover.nonce)throw new Error('The account nonce changed or a transaction is pending. Locate its hash in MetaMask instead.');setHistory(saveRecord({...recover,status:'rejected'}));setRecover(null);setNotice('Unsent request cleared after checking the account nonce.');}
  const disabled=!!busy||pending||!ready;
  const canReview=!!batch&&!!wallet&&storageOK&&!disabled&&(!batch.duplicates.length||allowDuplicates)&&(!previous||allowRepeat);
  return <main className="desk">
    <header><div className="brand"><span className="mark">↗</span> Batch <b>Desk</b></div><span className="network">● Ethereum mainnet</span><button className="wallet-button" disabled={!!busy||!CONFIGURED} onClick={()=>run('Connecting…',connect)}><Wallet size={16}/>{wallet?short(wallet.account):'Connect MetaMask'}</button></header>
    <div className="titlebar"><div><p className="eyebrow">PERSONAL USDT PAYMENTS</p><h1>One batch. All your payments.</h1></div><div className="contract-badge"><ShieldCheck size={18}/><div>Your contract<a href={`https://etherscan.io/address/${CONTRACT}`} target="_blank" rel="noreferrer">{short(CONTRACT)} ↗</a></div></div></div>
    <div>{!CONFIGURED&&<div className="message" role="status">Local setup required: fill in config.local.json and run npm run package:local. Wallet access stays disabled until configured.</div>}</div><div className="steps"><span className="active"><b>01</b> Configure</span><i/><span><b>02</b> Review & approve</span><i/><span><b>03</b> Sign & send</span></div>
    {error&&<div className="message error" role="alert">{error}{/mainnet/.test(error)&&<button className="quiet" disabled={!!busy} onClick={()=>run('Switching…',async()=>{await injected?.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x1'}]});await refresh()})}>Switch to Ethereum</button>}</div>}
    {notice&&<div className="message" role="status">{notice}</div>}
    <div className="workspace"><div><section className="paper">
      <div className="section-head"><div><label className="small-label" htmlFor="batch-name">BATCH NAME</label><input id="batch-name" className="name-input" value={title} maxLength={80} disabled={disabled} onChange={e=>setTitle(e.target.value)}/></div><span className="saved"><Check size={14}/>{ready&&storageOK?'Saved in this browser':'Local draft'}</span></div>
      <Tabs value={mode} onValueChange={v=>setMode(String(v))}><div className="editor-tools"><TabsList><TabsTrigger value="rows">Enter recipients</TabsTrigger><TabsTrigger value="paste">Paste a list</TabsTrigger></TabsList><button className="text-button" disabled={disabled} onClick={()=>fileRef.current?.click()}><Upload size={15}/>Import CSV</button><input ref={fileRef} type="file" accept=".csv,.txt,text/csv,text/plain" hidden onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>200000)setError('The import is too large. Use at most 500 rows.');else importText(await f.text())}e.target.value=''}}/></div>
      <TabsContent value="rows"><Table><TableHeader><TableRow><TableHead>#</TableHead><TableHead>Ethereum recipient</TableHead><TableHead className="amount-heading">Amount · USDT</TableHead><TableHead><span className="sr-only">Remove</span></TableHead></TableRow></TableHeader><TableBody>{rows.map((row,i)=><TableRow key={i}><TableCell>{String(i+1).padStart(2,'0')}</TableCell><TableCell><input className="address-input" spellCheck={false} autoComplete="off" aria-label={`Recipient ${i+1}`} placeholder="0x… Ethereum address" value={row.address} disabled={disabled} onChange={e=>setRows(rows.map((r,j)=>i===j?{...r,address:e.target.value}:r))}/></TableCell><TableCell><input className="amount-input" inputMode="decimal" aria-label={`Amount ${i+1} in USDT`} placeholder="0.00" value={row.amount} disabled={disabled} onChange={e=>setRows(rows.map((r,j)=>i===j?{...r,amount:e.target.value}:r))}/></TableCell><TableCell><button className="icon-button" aria-label={`Remove recipient ${i+1}`} disabled={disabled} onClick={()=>setRows(rows.length===1?blank():rows.filter((_,j)=>j!==i))}><Trash2 size={15}/></button></TableCell></TableRow>)}</TableBody></Table><div className="editor-bottom"><button className="quiet" disabled={disabled||rows.length>=500} onClick={()=>setRows([...rows,{address:'',amount:''}])}><Plus size={15}/>Add recipient</button><span>{rows.length} {rows.length===1?'row':'rows'} · up to 6 decimals</span></div></TabsContent>
      <TabsContent value="paste"><div className="paste-panel"><label htmlFor="paste-list">One address and USDT amount per line. Commas, tabs, or spaces.</label><textarea id="paste-list" placeholder={'0x…address, 25.50\n0x…address, 100'} rows={7} spellCheck={false} value={paste} disabled={disabled} onChange={e=>setPaste(e.target.value)}/><button className="quiet" disabled={disabled||!paste.trim()} onClick={()=>importText(paste)}>Use this list</button><p>Import replaces the current rows only after every line passes validation.</p></div></TabsContent></Tabs>
      {!empty&&validation.error&&<div className="validation" role="status">{validation.error}</div>}
      <div className="paper-footer"><button className="text-button" disabled={!batch||!!busy} onClick={()=>{try{download(toCSV(rows),'usdt-batch.csv')}catch(e){setError(friendlyError(e))}}}><Download size={14}/>Export CSV</button><button className="text-button" disabled={disabled} onClick={()=>setClearOpen(true)}>New batch</button></div>
    </section>
    <div className="privacy-note"><ShieldCheck size={16}/><span>Drafts and history stay in this browser. Payments are public on Ethereum after you sign.</span></div>
    <section className="history"><div className="section-head"><h2>Transaction history</h2><button className="text-button" disabled={!!busy||!injected} onClick={()=>run('Checking receipts…',refresh)}><RefreshCw size={14}/>Refresh</button></div>{history.length===0?<div className="history-empty"><FileText size={26}/><div>No payments sent from this interface yet.<small>Pending transactions and receipts will appear here.</small></div></div>:<div className="history-list">{history.map(h=><article key={h.id}><div><strong>{h.kind==='send'?h.title:labels[h.kind]}</strong><small>{new Date(h.created).toLocaleString()} · {h.kind==='send'?`${h.count} recipients · ${h.total} USDT`:h.kind==='approve'?`${h.total} USDT`:'0 USDT allowance'}</small></div><div className="history-status"><span className={`status ${h.status}`}>{h.status==='signing'?'Awaiting signature':h.status}</span>{h.hash&&<a href={`https://etherscan.io/tx/${h.hash}`} target="_blank" rel="noreferrer">View transaction ↗</a>}{['pending','signing','unknown'].includes(h.status)&&<button className="text-button" onClick={()=>{setRecover(h);setRecoveryHash('')}}>Resolve request</button>}</div></article>)}</div>}{history.length>0&&<button className="text-button export-history" onClick={()=>download(JSON.stringify(history,null,2),'usdt-transaction-history.json','application/json')}><Download size={14}/>Export history</button>}</section>
    </div><aside><section className="summary"><p className="eyebrow">BATCH TOTAL</p><div className="total">{batch?usdt(batch.total):'0.00'} <small>USDT</small></div><div className="summary-line"><span>Recipients</span><b>{batch?.rows.length??'—'}</b></div><div className="summary-line"><span>Available USDT</span><b>{wallet?usdt(wallet.balance):'Connect wallet'}</b></div><div className="summary-line"><span>Contract fee</span><b>0 USDT</b></div><div className="summary-line"><span>Allowance</span><b>{wallet?usdt(wallet.allowance)+' USDT':'—'}</b></div><div className="summary-divider"/>
      {batch&&batch.duplicates.length>0&&<label className="check-line warning"><Checkbox checked={allowDuplicates} onCheckedChange={v=>setAllowDuplicates(v===true)}/><span>{batch.duplicates.length} repeated address(es). Pay each row separately.</span></label>}
      {previous&&<label className="check-line warning"><Checkbox checked={allowRepeat} onCheckedChange={v=>setAllowRepeat(v===true)}/><span>This payment list was already sent. I intend to pay it again.</span></label>}
      <p>{pending?'A request is still open. Check transaction history before sending again.':!wallet?'Connect the Ledger owner account through MetaMask.':step==='reset'?'USDT needs the existing allowance reset to zero before approving this batch.':step==='approve'?'Approve only this batch’s total, then review and send the payment.':'Allowance is ready. Review every recipient and the network fee before sending.'}</p>
      <button className="primary" disabled={!CONFIGURED||(wallet?!canReview:!!busy)} onClick={()=>wallet?run('Checking batch…',()=>review(step)):run('Connecting…',connect)}>{busy||(!wallet?'Connect MetaMask':labels[step])}<ArrowUpRight size={17}/></button>
      <p className="ledger-note">You sign each transaction on your Ledger.<br/>Network fees are paid separately in ETH.</p>
      {wallet&&wallet.allowance>0n&&<button className="revoke-button" disabled={!storageOK||disabled} onClick={()=>run('Checking allowance…',()=>review('revoke'))}>Revoke unused allowance</button>}
    </section><details className="contract-details"><summary>Contract & wallet details</summary><label>Batch contract</label><a href={`https://etherscan.io/address/${CONTRACT}`} target="_blank" rel="noreferrer">{CONTRACT}</a><label>Owner</label><span>{OWNER}</span><label>USDT on Ethereum</label><a href={`https://etherscan.io/token/${TOKEN}`} target="_blank" rel="noreferrer">{TOKEN}</a><p>One transaction pays the whole batch. If a transfer fails, every payment in that batch reverts.</p></details></aside></div>
    <footer><span>USDT Batch Desk</span><span>Ethereum mainnet · PersonalUSDTBatch</span></footer>
    <Dialog open={!!plan} onOpenChange={open=>{if(!open&&!busy)setPlan(null)}}><DialogContent className="review-dialog" showCloseButton={!busy}><DialogTitle>{plan?labels[plan.kind]:''}</DialogTitle><DialogDescription>Ethereum mainnet · Ledger owner account {short(OWNER)}</DialogDescription>{error&&<p role="alert" className="validation">{error}</p>}{plan&&<><div className="review-amount">{plan.kind==='reset'||plan.kind==='revoke'?'0':usdt(plan.batch.total)} <small>USDT {plan.kind==='send'?'to recipients':'allowance'}</small></div><p className="review-address">{plan.kind==='send'?'Batch contract':'Approved spender'}<code>{CONTRACT}</code></p>{plan.kind==='send'&&<div className="review-recipients"><Table><TableHeader><TableRow><TableHead>Recipient</TableHead><TableHead>USDT</TableHead></TableRow></TableHeader><TableBody>{plan.batch.rows.map((r,i)=><TableRow key={i}><TableCell className="full-address">{r.address}</TableCell><TableCell>{r.amount}</TableCell></TableRow>)}</TableBody></Table></div>}<p>Estimated maximum network fee: <b>{plan.fee} ETH</b><br/><small>MetaMask displays the final fee before you sign.</small></p><label className="check-line"><Checkbox checked={reviewed} disabled={!!busy} onCheckedChange={v=>setReviewed(v===true)}/><span>I checked {plan.kind==='send'?'every recipient and amount':'the spender and allowance amount'}.</span></label><button className="primary" disabled={!reviewed||!!busy} onClick={()=>run('Waiting for Ledger…',sign)}>{busy||'Continue to MetaMask'}<ArrowUpRight size={17}/></button></>}</DialogContent></Dialog>
    <AlertDialog open={clearOpen} onOpenChange={setClearOpen}><AlertDialogContent><AlertDialogTitle>Start a new batch?</AlertDialogTitle><AlertDialogDescription>This clears the current draft. Export it first if you want to use it again. Transaction history stays saved.</AlertDialogDescription><div className="actions"><AlertDialogCancel>Keep editing</AlertDialogCancel><button className="quiet" onClick={()=>{setRows(blank());setTitle('My USDT batch');setClearOpen(false);setNotice('New batch ready.')}}>New batch</button></div></AlertDialogContent></AlertDialog>
    <Dialog open={!!recover} onOpenChange={open=>{if(!open)setRecover(null)}}><DialogContent><DialogTitle>Resolve an unfinished request</DialogTitle><DialogDescription>Check MetaMask Activity first. If the transaction was submitted, paste its transaction hash. Do not repeat the payment.</DialogDescription>{error&&<p role="alert" className="validation">{error}</p>}<input aria-label="Transaction hash" placeholder="0x… transaction hash" value={recoveryHash} onChange={e=>setRecoveryHash(e.target.value)}/><button className="quiet" disabled={!!busy} onClick={()=>run('Checking transaction…',recoverByHash)}>Find transaction</button><p className="muted">If you rejected or closed the request in MetaMask and nothing was submitted, clear it below. The account nonce will be checked first.</p><button className="text-button" disabled={!!busy} onClick={()=>run('Checking account nonce…',clearUnsent)}>I canceled it in MetaMask — check & clear</button></DialogContent></Dialog>
  </main>
}
